## NumPy Operations

In [1]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"Basic Slicing {arr[2 : 7]}")
print(f"With step {arr[1 : 8 : 2]}")
print(f"Negative indexing {arr[-3]}")


Basic Slicing [3 4 5 6 7]
With step [2 4 6 8]
Negative indexing 8


In [7]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(f"Specific element {arr_2d[1, 2]}")
print(f"Entire Row : {arr_2d[1]}")
print(f"Entire Column : {arr_2d[:, 1]}")

Specific element 6
Entire Row : [4 5 6]
Entire Column : [2 5 8]


## Sorting Array

In [14]:
unsorted = np.array([2, 5, 6, 3, 8, 9, 0, 1, 9, 8])
print(f"Sorted Array : {np.sort(unsorted)}")

unsorted_2d = np.array([[1, 6, 3],
                        [9, 5, 3],
                        [10, 9, 4]])

print(f"Sorted array:\n {np.sort(unsorted_2d, axis=0)} ")

Sorted Array : [0 1 2 3 5 6 8 8 9 9]
Sorted array:
 [[ 1  5  3]
 [ 9  6  3]
 [10  9  4]] 


## Filter

In [16]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print(f"Even Array :\n {even_number}")

Even Array :
 [ 2  4  6  8 10]


## Filter with Mask

In [17]:
mask = numbers > 5
print(f"Numbers greater than 5:\n {numbers[mask]}")


Numbers greater than 5:
 [ 6  7  8  9 10]


## Fancy indexes and NumPy Where()

In [21]:
indices = [0, 1, 4]
print(f"Numbers :\n {numbers[indices]}")

where_NP = np.where(numbers > 5)
print(f"Numbers greater than 5:\n {numbers[where_NP]}")


Numbers :
 [1 2 5]
Numbers greater than 5:
 [ 6  7  8  9 10]


In [23]:
array_condition = np.where(numbers > 5, numbers*2, numbers)
print(array_condition)

[ 1  2  3  4  5 12 14 16 18 20]


## Combining Two Arrays

In [24]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)


[1 2 3 4 5 6]


## Shape Compatibility

In [26]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9, 4])

print(f"Shape Compatibility {a.shape == b.shape}")
print(f"Shape Compatibility {a.shape == c.shape}")



Shape Compatibility True
Shape Compatibility False


In [28]:
# Add New Row
orignal = np.array([[1, 2, 3], [4, 5, 6]])
new_row = np.array([7, 8, 9])

with_new_row = np.vstack((orignal, new_row))
print(with_new_row)

# Add New Column
new_col = np.array([[10], [11]])
with_new_col = np.hstack((orignal, new_col))
print(with_new_col)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3 10]
 [ 4  5  6 11]]


In [30]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print(f"Array after deletion:\n {deleted}")


Array after deletion:
 [1 2 4 5]
