In [2]:
import numpy as np
import time



## creating array from list

In [3]:
arr_1D = np.array([1, 2, 3])
print(f"1D Array : {arr_1D}")

arr_2D = np.array([[1, 2, 3], [4, 5, 6]])
print(f"2D Array : {arr_2D}")

1D Array : [1 2 3]
2D Array : [[1 2 3]
 [4 5 6]]


### List VS Array

In [4]:
py_list = [1, 2, 3]
print(f"List Multipilication : {py_list * 2}")

np_array = np.array([1, 2, 3])
print(f"Array Multiplication : {np_array * 2}")


start = time.time()
py_list = [i*2 for i in range(1000000)]
print(f"'List' multiplication Operation Time : {time.time() - start}")

start = time.time()
np_array = np.arange(1000000)
print(f"'Array' multiplication Operation Time : {time.time() - start}")

List Multipilication : [1, 2, 3, 1, 2, 3]
Array Multiplication : [2 4 6]
'List' multiplication Operation Time : 0.18703603744506836
'Array' multiplication Operation Time : 0.0025742053985595703


### creating array from scratch

In [5]:
zero = np.zeros((3, 4))
print(f"Zero array : \n {zero}")

one = np.ones((2, 3))
print(f"Ones array : \n {one}")


full = np.full((2, 2), 7)
print(f"Full array : \n {full}")

random = np.random.random((2, 3))
print(f"Random array : \n {random}")

sequence = np.arange(0, 10, 2)
print(f"Sequence array : \n {sequence}")

Zero array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array : 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array : 
 [[7 7]
 [7 7]]
Random array : 
 [[0.15313773 0.56711041 0.56031719]
 [0.28544757 0.40867692 0.09327991]]
Sequence array : 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [6]:
vector = np.array([1, 2, 3])
print(f"Vetor : {vector}")

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print(f"Matrix : {matrix}")

tensor = np.array([[[1, 2], [3, 4]],
                    [[5, 6], [7, 8]]])
print(f"Tensor : {tensor}")

Vetor : [1 2 3]
Matrix : [[1 2 3]
 [4 5 6]]
Tensor : [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(f"shape: {arr.shape}")
print(f"size: {arr.size}")
print(f"Dtype: {arr.dtype}")
print(f"Dimension: {arr.ndim}")

shape: (2, 3)
size: 6
Dtype: int64
Dimension: 2


### Array Reshaping

In [8]:
arr = np.arange(12)
print(f"Orignal Array:\n {arr}")

reshaped = arr.reshape((3, 4))
print(f"Reshape Array:\n {reshaped}")

flattened = reshaped.flatten()
print(f"Flattened Array:\n {flattened}")

# revel (return view, insted of copy)
ravelled = reshaped.ravel()
print(f"Ravelled Array:\n {ravelled}")

# Transpose
transpose = reshaped.T
print(f"Transposed Array:\n {transpose}")



Orignal Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshape Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravelled Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
