In [2]:
import numpy as np

# Load Data file in NumPy

data = np.loadtxt("Data/student_marks.csv", delimiter=",", skiprows=1)
print(data)

[[ 1. 78. 69. 84. 75. 92.]
 [ 2. 85. 77. 89. 83. 95.]
 [ 3. 62. 58. 70. 65. 60.]
 [ 4. 90. 88. 94. 91. 96.]
 [ 5. 55. 60. 57. 63. 52.]
 [ 6. 80. 72. 78. 74. 85.]
 [ 7. 68. 65. 60. 70. 72.]
 [ 8. 88. 82. 90. 86. 91.]
 [ 9. 73. 70. 68. 72. 75.]
 [10. 95. 93. 97. 94. 98.]]


In [3]:
# shape of given data

print(f"Data shape : {data.shape}")

Data shape : (10, 6)


In [4]:
# Extract Computer Science Column

computer_sci = data[ : , 5]
print(f"Computer science marks : {computer_sci}")

Computer science marks : [92. 95. 60. 96. 52. 85. 72. 91. 75. 98.]


In [5]:
# Avg of each student

avg = np.mean(data[ : , 1 : ], axis=1)
print(f"Avgerage of each student : {avg}")

Avgerage of each student : [79.6 85.8 63.  91.8 57.4 77.8 67.  87.4 71.6 95.4]


In [6]:
# Avgerage of each subject 

avg_sub = np.mean(data[ : , 1 : ], axis=0)
print(F"Average of each subject : \n {avg_sub}")

Average of each subject : 
 [77.4 73.4 78.7 77.3 81.6]


In [7]:
# Extract column of maths

maths = data[ : , 1]
print(f"Maths marks : {maths}")


Maths marks : [78. 85. 62. 90. 55. 80. 68. 88. 73. 95.]


In [8]:
# Get Max marks in physics 

max_phy = np.max(data[ : , 2])
print(f"Maximum marks in physics : {max_phy}")


Maximum marks in physics : 93.0


In [9]:
# standard deviation of marks 

std_marks = np.std(data[ : , 1 : ]) 
print(f"Standard deviation of marks : {std_marks}")

Standard deviation of marks : 12.8521437900453


In [10]:
# Sort english column 

sorted_eng_col = np.sort(data[ : , 3])
print(f"Sorted english column : {sorted_eng_col}")

Sorted english column : [57. 60. 68. 70. 78. 84. 89. 90. 94. 97.]


In [11]:
# Dimension of Given data

print(f"Dimension of data: \n {data.ndim}")

Dimension of data: 
 2


In [12]:
# flattened data

flattened_data = data.flatten()
print(f"Flattened data: \n  {flattened_data}")

Flattened data: 
  [ 1. 78. 69. 84. 75. 92.  2. 85. 77. 89. 83. 95.  3. 62. 58. 70. 65. 60.
  4. 90. 88. 94. 91. 96.  5. 55. 60. 57. 63. 52.  6. 80. 72. 78. 74. 85.
  7. 68. 65. 60. 70. 72.  8. 88. 82. 90. 86. 91.  9. 73. 70. 68. 72. 75.
 10. 95. 93. 97. 94. 98.]


In [13]:
# Transposing data 

transposed_data = data.transpose()
print(f"Transposed data : \n {transposed_data}")

Transposed data : 
 [[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [78. 85. 62. 90. 55. 80. 68. 88. 73. 95.]
 [69. 77. 58. 88. 60. 72. 65. 82. 70. 93.]
 [84. 89. 70. 94. 57. 78. 60. 90. 68. 97.]
 [75. 83. 65. 91. 63. 74. 70. 86. 72. 94.]
 [92. 95. 60. 96. 52. 85. 72. 91. 75. 98.]]


In [14]:
# Slicing

sliced_data = data[1 : , 1 : ] # ROWS(1 : END), COLUMNS(1 : END)
print(f"Data without 'id' column : \n {sliced_data}")



Data without 'id' column : 
 [[85. 77. 89. 83. 95.]
 [62. 58. 70. 65. 60.]
 [90. 88. 94. 91. 96.]
 [55. 60. 57. 63. 52.]
 [80. 72. 78. 74. 85.]
 [68. 65. 60. 70. 72.]
 [88. 82. 90. 86. 91.]
 [73. 70. 68. 72. 75.]
 [95. 93. 97. 94. 98.]]


In [15]:
# slicing with steps

step_slicing = data[1 : : 2, 1 : : 2] #(ROW : END : STEPS), (COLUMN : END : STEPS)
print(f"Slicing with steps : \n { step_slicing}")


Slicing with steps : 
 [[85. 89. 95.]
 [90. 94. 96.]
 [80. 78. 85.]
 [88. 90. 91.]
 [95. 97. 98.]]


In [16]:
# Negative indexing 

neg_idx = data[ : , -4 : ] #(ROW ' : ') (COLUMN '-4 : ')
print(f"Negative indexing in 2d array : \n {neg_idx}")

Negative indexing in 2d array : 
 [[69. 84. 75. 92.]
 [77. 89. 83. 95.]
 [58. 70. 65. 60.]
 [88. 94. 91. 96.]
 [60. 57. 63. 52.]
 [72. 78. 74. 85.]
 [65. 60. 70. 72.]
 [82. 90. 86. 91.]
 [70. 68. 72. 75.]
 [93. 97. 94. 98.]]


In [22]:
# Data sorted (Column wise)

sorted_data_column_wise = np.sort(data, axis=0)
print(f"Sorted data COLUMN wise : \n {sorted_data_column_wise}")

# Data sorted (Row wise)

sorted_data_row_wise = np.sort(data)
print(f"Sotred data ROW wise : \n {sorted_data_row_wise}")

Sorted data COLUMN wise : 
 [[ 1. 55. 58. 57. 63. 52.]
 [ 2. 62. 60. 60. 65. 60.]
 [ 3. 68. 65. 68. 70. 72.]
 [ 4. 73. 69. 70. 72. 75.]
 [ 5. 78. 70. 78. 74. 85.]
 [ 6. 80. 72. 84. 75. 91.]
 [ 7. 85. 77. 89. 83. 92.]
 [ 8. 88. 82. 90. 86. 95.]
 [ 9. 90. 88. 94. 91. 96.]
 [10. 95. 93. 97. 94. 98.]]
Sotred data ROW wise : 
 [[ 1. 69. 75. 78. 84. 92.]
 [ 2. 77. 83. 85. 89. 95.]
 [ 3. 58. 60. 62. 65. 70.]
 [ 4. 88. 90. 91. 94. 96.]
 [ 5. 52. 55. 57. 60. 63.]
 [ 6. 72. 74. 78. 80. 85.]
 [ 7. 60. 65. 68. 70. 72.]
 [ 8. 82. 86. 88. 90. 91.]
 [ 9. 68. 70. 72. 73. 75.]
 [10. 93. 94. 95. 97. 98.]]


### Filtering Data

In [26]:
even_numbers = data[data % 2 == 0]
print(f"Even numbers in Given data : \n {even_numbers}")

odd_numbers = data[data % 2 != 0]
print(f"Odd numbers in Given data : \n {odd_numbers}")

# Filter with mask

mask = data > 90
print(f"Marks greater than 90 : \n {data[mask]}")

Even numbers in Given data : 
 [78. 84. 92.  2. 62. 58. 70. 60.  4. 90. 88. 94. 96. 60. 52.  6. 80. 72.
 78. 74. 68. 60. 70. 72.  8. 88. 82. 90. 86. 70. 68. 72. 10. 94. 98.]
Odd numbers in Given data : 
 [ 1. 69. 75. 85. 77. 89. 83. 95.  3. 65. 91.  5. 55. 57. 63. 85.  7. 65.
 91.  9. 73. 75. 95. 93. 97.]
Marks greater than 90 : 
 [92. 95. 94. 91. 96. 91. 95. 93. 97. 94. 98.]


In [33]:
# Fancy indexing 

indexes = [0, 4, 5, 9]
print(f"Numbers of given indexes : \n {data[indexes]}")

# using where() in NumPy

num = np.where(data > 80)
print(f"Marks greater than 80 : \n {data[num]}")

# conditions in where()

num_condition = np.where(data > 80 , data * 2, data)
print(f"Data with 80 multiplied by 2 : \n {num_condition}")

Numbers of given indexes : 
 [[ 1. 78. 69. 84. 75. 92.]
 [ 5. 55. 60. 57. 63. 52.]
 [ 6. 80. 72. 78. 74. 85.]
 [10. 95. 93. 97. 94. 98.]]
Marks greater than 80 : 
 [84. 92. 85. 89. 83. 95. 90. 88. 94. 91. 96. 85. 88. 82. 90. 86. 91. 95.
 93. 97. 94. 98.]
Data with 80 multiplied by 2 : 
 [[  1.  78.  69. 168.  75. 184.]
 [  2. 170.  77. 178. 166. 190.]
 [  3.  62.  58.  70.  65.  60.]
 [  4. 180. 176. 188. 182. 192.]
 [  5.  55.  60.  57.  63.  52.]
 [  6.  80.  72.  78.  74. 170.]
 [  7.  68.  65.  60.  70.  72.]
 [  8. 176. 164. 180. 172. 182.]
 [  9.  73.  70.  68.  72.  75.]
 [ 10. 190. 186. 194. 188. 196.]]


In [51]:
data1 = np.loadtxt("Data2/Data1.csv", delimiter=",",  skiprows=1)
print(f"Data1 : \n{data1}")

Data1 : 
[[ 1. 78. 85.]
 [ 2. 88. 90.]
 [ 3. 92. 87.]
 [ 4. 76. 80.]]


In [52]:
data2 = np.loadtxt("Data2/Data2.csv", delimiter=",", skiprows=1)
print(f"Data2 : \n{data2}")

Data2 : 
[[ 5. 81. 79.]
 [ 6. 89. 91.]
 [ 7. 84. 88.]
 [ 8. 90. 86.]]


In [47]:
# Concatenating two different data

data_concat = np.concatenate(data1 + data2)
print(f"Concatenated data : \n {data_concat}")

Concatenated data : 
 [  6. 159. 164.   8. 177. 181.  10. 176. 175.  12. 166. 166.]


In [62]:
# Adding a new row to data1

new_row = np.array([5., 99., 99.])

new_data1 = np.vstack((data1, new_row))
print(f"Updated data1 : \n {new_data1}")

# Adding new column to data2

new_column = np.array([[9.], [10.], [11.], [12.]])
new_data2 = np.hstack((data2, new_column))
print(f"Updating data2 : \n {new_data2}")

Updated data1 : 
 [[ 1. 78. 85.]
 [ 2. 88. 90.]
 [ 3. 92. 87.]
 [ 4. 76. 80.]
 [ 5. 99. 99.]]
Updating data2 : 
 [[ 5. 81. 79.  9.]
 [ 6. 89. 91. 10.]
 [ 7. 84. 88. 11.]
 [ 8. 90. 86. 12.]]


In [69]:
print(data1)
deleted_data = np.delete(data1,0)
print(f"Deleted data : \n {deleted_data}")

[[ 1. 78. 85.]
 [ 2. 88. 90.]
 [ 3. 92. 87.]
 [ 4. 76. 80.]]
Deleted data : 
 [78. 85.  2. 88. 90.  3. 92. 87.  4. 76. 80.]
