In [ ]:
import numpy as np

# Load Data file in NumPy

data = np.loadtxt("Data/student_marks.csv", delimiter=",", skiprows=1)
print(data)

[[ 1. 78. 69. 84. 75. 92.]
 [ 2. 85. 77. 89. 83. 95.]
 [ 3. 62. 58. 70. 65. 60.]
 [ 4. 90. 88. 94. 91. 96.]
 [ 5. 55. 60. 57. 63. 52.]
 [ 6. 80. 72. 78. 74. 85.]
 [ 7. 68. 65. 60. 70. 72.]
 [ 8. 88. 82. 90. 86. 91.]
 [ 9. 73. 70. 68. 72. 75.]
 [10. 95. 93. 97. 94. 98.]]


In [ ]:
# shape of given data

print(f"Data shape : {data.shape}")

Data shape : (10, 6)


In [5]:
# Extract Computer Science Column

computer_sci = data[ : , 5]
print(f"Computer science marks : {computer_sci}")

Computer science marks : [92. 95. 60. 96. 52. 85. 72. 91. 75. 98.]


In [ ]:
# Avg of each student

avg = np.mean(data[ : , 1 : ], axis=1)
print(f"Avgerage of each student : {avg}")

Avgerage of each student : [79.6 85.8 63.  91.8 57.4 77.8 67.  87.4 71.6 95.4]


In [7]:
# Avgerage of each subject 

avg_sub = np.mean(data[ : , 1 : ], axis=0)
print(F"Average of each subject : \n {avg_sub}")

Average of each subject : 
 [77.4 73.4 78.7 77.3 81.6]


In [8]:
# Extract column of maths

maths = data[ : , 1]
print(f"Maths marks : {maths}")


Maths marks : [78. 85. 62. 90. 55. 80. 68. 88. 73. 95.]


In [10]:
# Get Max marks in physics 

max_phy = np.max(data[ : , 2])
print(f"Maximum marks in physics : {max_phy}")


Maximum marks in physics : 93.0


In [11]:
# standard deviation of marks 

std_marks = np.std(data[ : , 1 : ]) 
print(f"Standard deviation of marks : {std_marks}")

Standard deviation of marks : 12.8521437900453


In [12]:
# Sort english column 

sorted_eng_col = np.sort(data[ : , 3])
print(f"Sorted english column : {sorted_eng_col}")

Sorted english column : [57. 60. 68. 70. 78. 84. 89. 90. 94. 97.]
